# Generated by Django 5.1 on 2024-08-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passkey',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral',
        ),
    ]
