# Generated by Django 5.1 on 2024-08-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_country_remove_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms',
            field=models.BooleanField(default=True),
        ),
    ]
