# Generated by Django 5.1 on 2024-09-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contractquestion_alter_user_managers_dispute_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table=None,
        ),
    ]
