# Generated by Django 5.1 on 2024-09-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_protectionfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='image',
        ),
        migrations.AlterField(
            model_name='disputeimage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
