# Generated by Django 5.1 on 2024-09-16 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_dispute_image_alter_disputeimage_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='agreement',
            unique_together={('receiver', 'product', 'question')},
        ),
    ]
