# Generated by Django 5.1 on 2024-10-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_referral_user_referral_code_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_on_milestone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_request',
            field=models.BooleanField(default=False),
        ),
    ]
