# Generated by Django 5.1 on 2024-10-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referral',
        ),
    ]
